"""Initial migration

Revision ID: 04f74935f474
Revises:
Create Date: 2026-03-27 10:05:52.866044

"""

import asyncio
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04f74935f474'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency'), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='paymentstatus'), nullable=False),
        sa.Column('idempotency_key', sa.String(length=36), nullable=False),
        sa.Column('webhook_url', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.Integer(), server_default='0', nullable=False),
        sa.Column('proceeded_at', sa.Integer(), server_default='0', nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('idempotency_key'),
    )
    op.create_table(
        'outbox',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('payment_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.Enum('PAYMENT', name='type'), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'RETRYING', 'SUCCEEDED', 'FAILED', name='outboxstatus'), nullable=False),
        sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.Column('last_attempt', sa.Integer(), server_default='0', nullable=False),
        sa.Column('created_at', sa.Integer(), server_default='0', nullable=False),
        sa.Column('scheduled_at', sa.Integer(), server_default='0', nullable=False),
        sa.Column('error', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ['payment_id'],
            ['payment.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    ## rabbitmq
    async def create_queue():
        from faststream.rabbit import RabbitBroker, RabbitQueue

        broker = RabbitBroker("amqp://root:privetserver@rabbit-mq:5672/")

        async with broker:
            queue_to_create = RabbitQueue("payments.new", durable=True)
            dlq_to_create = RabbitQueue("payments.dlq", durable=True)
            for q in (queue_to_create, dlq_to_create):
                await broker.declare_queue(q)

    asyncio.run(create_queue())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox')
    op.drop_table('payment')
    # ### end Alembic commands ###
